import React, { useState, useEffect } from 'react';
import { Search, Download, Filter, Eye, X, MessageSquare, User, Mail, Phone, Calendar } from 'lucide-react';

export default function AILeadsTab({ token, showSuccess }) {
  const [leads, setLeads] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState('All');
  const [selectedLead, setSelectedLead] = useState(null);
  const [selectedIds, setSelectedIds] = useState([]);

  const handleSelectAll = (e) => {
    if (e.target.checked) {
      setSelectedIds(filteredLeads.map(l => l._id));
    } else {
      setSelectedIds([]);
    }
  };

  const handleSelect = (id) => {
    setSelectedIds(prev => prev.includes(id) ? prev.filter(i => i !== id) : [...prev, id]);
  };

  const handleBulkUpdate = async (status) => {
    if (!window.confirm(`Are you sure you want to mark ${selectedIds.length} leads as ${status}?`)) return;
    try {
      setLoading(true);
      await Promise.all(selectedIds.map(id =>
        fetch(`${import.meta.env.VITE_API_URL}/api/ai-leads/${id}`, {
          method: 'PATCH',
          headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
          body: JSON.stringify({ status })
        })
      ));
      showSuccess(`Successfully marked ${selectedIds.length} leads as ${status}`);
      setSelectedIds([]);
      fetchLeads();
    } catch (err) {
      console.error(err);
      alert('Failed to update some leads.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchLeads();
  }, []);

  const fetchLeads = async () => {
    try {
      const res = await fetch(`${import.meta.env.VITE_API_URL}/api/ai-leads`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      if (res.ok) {
        setLeads(await res.json());
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const updateStatus = async (id, newStatus) => {
    try {
      const res = await fetch(`h${import.meta.env.VITE_API_URL}0/api/ai-leads/${id}`, {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify({ status: newStatus })
      });
      if (res.ok) {
        showSuccess(`Status updated to ${newStatus}`);
        fetchLeads();
        if (selectedLead) setSelectedLead({ ...selectedLead, status: newStatus });
      }
    } catch (err) {
      console.error(err);
    }
  };

  const filteredLeads = leads.filter(l => {
    const matchesFilter = statusFilter === 'All' || l.status === statusFilter;
    const matchesSearch = l.name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      l.mobile?.includes(searchTerm) ||
      l.questionAsked?.toLowerCase().includes(searchTerm.toLowerCase());
    return matchesFilter && matchesSearch;
  });

  return (
    <div className="p-8">
      <div className="flex justify-between items-center mb-8">
        <div>
          <h2 className="text-2xl font-black text-slate-800">AI Assistant Leads</h2>
          <p className="text-xs font-semibold text-slate-400 mt-1">Manage leads generated by the AI Chatbot</p>
        </div>
        <div className="flex flex-wrap gap-3">
          <div className="relative">
            <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
            <input
              type="text"
              placeholder="Search leads..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pl-9 pr-4 py-2 bg-white border border-slate-200 rounded-xl text-xs font-semibold focus:outline-none focus:border-primary w-full sm:w-64 shadow-sm"
            />
          </div>
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="px-4 py-2 bg-white border border-slate-200 rounded-xl text-xs font-semibold focus:outline-none focus:border-primary shadow-sm"
          >
            <option value="All">All Statuses</option>
            <option value="New">New</option>
            <option value="Followed Up">Followed Up</option>
            <option value="Converted">Converted</option>
          </select>
          {selectedIds.length > 0 && (
            <div className="flex items-center gap-2 bg-slate-200 px-3 py-1.5 rounded-xl text-sm font-bold shadow-inner">
              <span className="text-slate-600 mr-2">{selectedIds.length} selected:</span>
              <button onClick={() => handleBulkUpdate('New')} className="px-3 py-1 bg-blue-500 hover:bg-blue-600 text-white rounded-lg shadow-sm text-xs">New</button>
              <button onClick={() => handleBulkUpdate('Followed Up')} className="px-3 py-1 bg-amber-500 hover:bg-amber-600 text-white rounded-lg shadow-sm text-xs">Follow Up</button>
              <button onClick={() => handleBulkUpdate('Converted')} className="px-3 py-1 bg-emerald-500 hover:bg-emerald-600 text-white rounded-lg shadow-sm text-xs">Convert</button>
            </div>
          )}
          <button className="px-4 py-2 bg-white border border-slate-200 text-slate-600 rounded-xl text-xs font-bold flex items-center gap-2 hover:bg-slate-50 shadow-sm">
            <Download size={14} /> Export
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
        <div className="bg-white p-6 rounded-2xl border border-slate-100 shadow-premium flex flex-col justify-between">
          <div className="text-slate-400 mb-2"><MessageSquare size={20} /></div>
          <div>
            <div className="text-2xl font-black text-slate-800">{leads.length}</div>
            <div className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">Total Conversations</div>
          </div>
        </div>
        <div className="bg-white p-6 rounded-2xl border border-slate-100 shadow-premium flex flex-col justify-between">
          <div className="text-blue-400 mb-2"><User size={20} /></div>
          <div>
            <div className="text-2xl font-black text-slate-800">{leads.filter(l => l.status === 'New').length}</div>
            <div className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">New Leads</div>
          </div>
        </div>
        <div className="bg-white p-6 rounded-2xl border border-slate-100 shadow-premium flex flex-col justify-between">
          <div className="text-amber-500 mb-2"><User size={20} /></div>
          <div>
            <div className="text-2xl font-black text-slate-800">{leads.filter(l => l.status === 'Followed Up').length}</div>
            <div className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">Followed Up</div>
          </div>
        </div>
        <div className="bg-white p-6 rounded-2xl border border-slate-100 shadow-premium flex flex-col justify-between">
          <div className="text-green-500 mb-2"><CheckCircle size={20} /></div>
          <div>
            <div className="text-2xl font-black text-slate-800">{leads.filter(l => l.status === 'Converted').length}</div>
            <div className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">Converted</div>
          </div>
        </div>
      </div>

      <div className="bg-white rounded-2xl border border-slate-100 shadow-premium overflow-hidden">
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="bg-slate-50 border-b border-slate-100 text-[10px] uppercase tracking-wider font-bold text-slate-500">
              <th className="p-4 w-12">
                <input type="checkbox" onChange={handleSelectAll} checked={filteredLeads.length > 0 && selectedIds.length === filteredLeads.length} className="w-4 h-4 rounded border-gray-300 text-primary focus:ring-primary cursor-pointer"/>
              </th>
              <th className="p-4">Date</th>
              <th className="p-4">Name</th>
              <th className="p-4">Contact</th>
              <th className="p-4">Question Asked</th>
              <th className="p-4">Status</th>
              <th className="p-4">Actions</th>
            </tr>
          </thead>
          <tbody className="text-xs font-semibold text-slate-700">
            {loading ? (
              <tr><td colSpan="6" className="p-8 text-center text-slate-400">Loading leads...</td></tr>
            ) : filteredLeads.length === 0 ? (
              <tr><td colSpan="6" className="p-8 text-center text-slate-400">No leads found.</td></tr>
            ) : (
              filteredLeads.map((lead) => (
                <tr key={lead._id} className="border-b border-slate-50 hover:bg-slate-50 transition-colors">
                  <td className="p-4">
                    <input type="checkbox" checked={selectedIds.includes(lead._id)} onChange={() => handleSelect(lead._id)} className="w-4 h-4 rounded border-gray-300 text-primary focus:ring-primary cursor-pointer"/>
                  </td>
                  <td className="p-4 whitespace-nowrap">{new Date(lead.createdAt).toLocaleDateString()}</td>
                  <td className="p-4 font-bold text-slate-800">{lead.name}</td>
                  <td className="p-4">
                    <div className="flex flex-col gap-1">
                      <a href={`tel:${lead.mobile}`} className="flex items-center gap-1 font-bold text-blue-600 hover:text-blue-800"><Phone size={10} /> {lead.mobile}</a>
                      {lead.email && <a href={`mailto:${lead.email}`} className="text-[10px] text-slate-500 hover:text-slate-800 flex items-center gap-1"><Mail size={10} /> {lead.email}</a>}
                    </div>
                  </td>
                  <td className="p-4 max-w-xs truncate">{lead.questionAsked || 'N/A'}</td>
                  <td className="p-4">
                    <span className={`px-2 py-1 rounded-md text-[10px] font-black uppercase tracking-wider ${lead.status === 'New' ? 'bg-blue-100 text-blue-700' :
                        lead.status === 'Converted' ? 'bg-emerald-100 text-emerald-700' :
                          lead.status === 'Followed Up' ? 'bg-amber-100 text-amber-700' :
                            'bg-slate-100 text-slate-700'
                      }`}>
                      {lead.status}
                    </span>
                  </td>
                  <td className="p-4 flex gap-2">
                    <button onClick={() => setSelectedLead(lead)} className="text-[10px] font-bold uppercase tracking-widest px-3 py-1 bg-slate-100 text-slate-600 rounded-lg hover:bg-slate-200 flex items-center gap-1">
                      <Eye size={12} /> View
                    </button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {/* Conversation Modal */}
      {selectedLead && (
        <div className="fixed inset-0 bg-slate-900/40 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-3xl shadow-2xl w-full max-w-3xl overflow-hidden flex flex-col max-h-[90vh]">
            <div className="p-6 border-b border-slate-100 flex justify-between items-start bg-slate-50">
              <div>
                <h3 className="text-xl font-black text-slate-800">{selectedLead.name}</h3>
                <p className="text-xs font-semibold text-slate-500 mt-1 flex items-center gap-4">
                  <span className="flex items-center gap-1"><Phone size={12} /> {selectedLead.mobile}</span>
                  <span className="flex items-center gap-1"><Mail size={12} /> {selectedLead.email}</span>
                  <span className="flex items-center gap-1"><Calendar size={12} /> {new Date(selectedLead.createdAt).toLocaleString()}</span>
                </p>
              </div>
              <button onClick={() => setSelectedLead(null)} className="p-2 hover:bg-slate-200 rounded-full transition-colors">
                <X size={20} />
              </button>
            </div>

            <div className="flex-1 overflow-y-auto p-6 bg-slate-100/50 space-y-4">
              <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-4 text-center">Conversation History</h4>

              {selectedLead.conversationHistory && selectedLead.conversationHistory.length > 0 ? (
                selectedLead.conversationHistory.map((msg, idx) => (
                  <div key={idx} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                    <div className={`max-w-[80%] p-4 rounded-2xl text-sm whitespace-pre-wrap ${msg.role === 'user' ? 'bg-primary text-white rounded-br-none' : 'bg-white border border-slate-200 text-slate-700 rounded-bl-none shadow-sm'}`}>
                      {msg.content}
                    </div>
                  </div>
                ))
              ) : (
                <p className="text-center text-sm text-slate-400">No conversation history available.</p>
              )}
            </div>

            <div className="p-6 border-t border-slate-100 bg-white flex justify-between items-center">
              <div className="flex items-center gap-3">
                <span className="text-xs font-bold text-slate-500">Update Status:</span>
                <select
                  value={selectedLead.status}
                  onChange={(e) => updateStatus(selectedLead._id, e.target.value)}
                  className="bg-slate-50 border border-slate-200 text-xs font-bold text-slate-700 rounded-lg px-3 py-2 outline-none focus:border-primary"
                >
                  <option value="New">New</option>
                  <option value="Followed Up">Followed Up</option>
                  <option value="Converted">Converted</option>
                  <option value="Archived">Archived</option>
                </select>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// Temporary CheckCircle polyfill since it wasn't imported at top to save space
function CheckCircle(props) {
  return <svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path><polyline points="22 4 12 14.01 9 11.01"></polyline></svg>;
}
